version: '3.8'

services:
  db_bootcamp_mariadb:
    image: mariadb:latest
    container_name: db_bootcamp_mariadb
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

